
CREATE SEQUENCE public.user_id_seq RESTART WITH 1;

CREATE SEQUENCE public.dictionary_id_seq RESTART WITH 1;

CREATE SEQUENCE public.progress_word_id_seq RESTART WITH 1;

CREATE TABLE public.dictionary (
    id BIGINT NOT NULL DEFAULT nextval('public.dictionary_id_seq'::regclass),
    translation VARCHAR(128) NOT NULL,
    word VARCHAR(128) NOT NULL,
    level VARCHAR(2),
    img_name VARCHAR(255),
    PRIMARY KEY (id)
);
--
--create table dictionary (
--    id int8 generated by default as identity,
--    img_name varchar(255),
--    level varchar(2),
--    translation varchar(255) not null,
--    word varchar(255) not null unique,
--    primary key (id)
--);

CREATE TABLE public.progress_word (
    id BIGINT NOT NULL DEFAULT nextval('public.progress_word_id_seq'::regclass),
    guessing_count INTEGER,
    last_revision_date TIMESTAMP WITHOUT TIME ZONE,
    learned_date TIMESTAMP WITHOUT TIME ZONE,
    revision_count INTEGER,
    studied BOOLEAN,
    word_id BIGINT,
    user_id BIGINT,
    PRIMARY KEY(id)
);

--create table progress_word (
--    id int8 generated by default as identity,
--    guessing_count int4, last_revision_date timestamp,
--    learned_date timestamp,
--    revision_count int4,
--    studied boolean,
--    user_id int8,
--    word_id int8,
--    primary key (id)
--);

create table user_role (
    user_id INT8 NOT NULL,
    roles VARCHAR(8)
);

CREATE TABLE public.users (
    id BIGINT NOT NULL DEFAULT nextval('public.user_id_seq'::regclass),
    login CHARACTER VARYING(64),
    name CHARACTER VARYING(32),
    password CHARACTER VARYING(255),
    date_of_birth DATE,
    e_mail CHARACTER VARYING(255),
    phone CHARACTER VARYING(13),
    avatar_name CHARACTER VARYING(255),
    level CHARACTER VARYING(255),
    PRIMARY KEY (id)
);
--
--create table users (
--    id int8 not null generated by default as identity,
--    avatar_name varchar(255),
--    date_of_birth date,
--    e_mail varchar(255),
--    level varchar(2),
--    login varchar(64) not null unique,
--    name varchar(64),
--    password varchar(255) not null,
--    phone varchar(13),
--    primary key (id)
--);

ALTER TABLE IF EXISTS progress_word ADD CONSTRAINT FK_Progress_Word_Users FOREIGN KEY (user_id) REFERENCES users;
ALTER TABLE IF EXISTS progress_word ADD CONSTRAINT FK_Progress_Word_Dictionary FOREIGN KEY (word_id) REFERENCES dictionary;
ALTER TABLE IF EXISTS user_role ADD CONSTRAINT FK_User_Role_Users FOREIGN KEY (user_id) REFERENCES users;
